"""add missing indexes and place dedup constraint

Revision ID: 10cae1a9cf19
Revises: e54f6232e325
Create Date: 2026-08-02 23:19:38.351175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cae1a9cf19'
down_revision: Union[str, Sequence[str], None] = 'e54f6232e325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """누락된 인덱스를 추가하고, 쓰이지 않는 visibility 컬럼을 제거한다.

    인덱스: PostgreSQL은 외래키 컬럼에 인덱스를 자동 생성하지 않는다. 없으면 JOIN이
    느릴 뿐 아니라 부모 행을 지울 때 자식 테이블을 전체 스캔한다.

    visibility 제거: 스페이스 모델 도입으로 접근 권한은 SpaceMember가 판단한다.
    남겨두면 "이 컬럼으로 권한을 검사해야 하나?" 하는 오해를 부르고 실제로 잘못된
    권한 검사를 짜게 된다. 외부 공개 기능은 별도 정책으로 다시 설계한다
    (docs/SPACE_MODEL_SPEC.md 10절).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_nl_diary_entries_author_id', 'nl_diary_entries', ['author_id'], unique=False)
    op.drop_column('nl_diary_entries', 'visibility')
    op.create_index('ix_nl_diary_photos_entry_order', 'nl_diary_photos', ['diary_entry_id', 'sort_order'], unique=False)
    op.create_index('ix_nl_diary_photos_uploader_id', 'nl_diary_photos', ['uploader_id'], unique=False)
    op.create_unique_constraint('uq_places_provider_place', 'nl_places', ['provider', 'provider_place_id'])
    op.create_index('ix_nl_schedule_participants_user_id', 'nl_schedule_participants', ['user_id'], unique=False)
    op.create_index('ix_nl_schedule_places_place_id', 'nl_schedule_places', ['place_id'], unique=False)
    op.create_index('ix_nl_schedule_places_schedule_order', 'nl_schedule_places', ['schedule_id', 'sort_order'], unique=False)
    op.drop_index(op.f('ix_nl_schedules_space_id'), table_name='nl_schedules')
    op.create_index('ix_nl_schedules_created_by', 'nl_schedules', ['created_by'], unique=False)
    op.create_index('ix_nl_schedules_space_start', 'nl_schedules', ['space_id', 'start_at'], unique=False)
    op.drop_column('nl_schedules', 'visibility')
    op.create_index('ix_nl_share_links_schedule_id', 'nl_share_links', ['schedule_id'], unique=False)
    op.create_index('ix_nl_space_members_user_status', 'nl_space_members', ['user_id', 'status'], unique=False)
    op.create_index('ix_nl_spaces_owner_id', 'nl_spaces', ['owner_id'], unique=False)
    op.create_index('ix_nl_users_default_space_id', 'nl_users', ['default_space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nl_users_default_space_id', table_name='nl_users')
    op.drop_index('ix_nl_spaces_owner_id', table_name='nl_spaces')
    op.drop_index('ix_nl_space_members_user_status', table_name='nl_space_members')
    op.drop_index('ix_nl_share_links_schedule_id', table_name='nl_share_links')
    op.add_column('nl_schedules', sa.Column('visibility', sa.VARCHAR(length=20), server_default=sa.text("'private'::character varying"), autoincrement=False, nullable=False))
    op.drop_index('ix_nl_schedules_space_start', table_name='nl_schedules')
    op.drop_index('ix_nl_schedules_created_by', table_name='nl_schedules')
    op.create_index(op.f('ix_nl_schedules_space_id'), 'nl_schedules', ['space_id'], unique=False)
    op.drop_index('ix_nl_schedule_places_schedule_order', table_name='nl_schedule_places')
    op.drop_index('ix_nl_schedule_places_place_id', table_name='nl_schedule_places')
    op.drop_index('ix_nl_schedule_participants_user_id', table_name='nl_schedule_participants')
    op.drop_constraint('uq_places_provider_place', 'nl_places', type_='unique')
    op.drop_index('ix_nl_diary_photos_uploader_id', table_name='nl_diary_photos')
    op.drop_index('ix_nl_diary_photos_entry_order', table_name='nl_diary_photos')
    op.add_column('nl_diary_entries', sa.Column('visibility', sa.VARCHAR(length=20), server_default=sa.text("'private'::character varying"), autoincrement=False, nullable=False))
    op.drop_index('ix_nl_diary_entries_author_id', table_name='nl_diary_entries')
    # ### end Alembic commands ###

    # autogenerate가 놓친 부분: 컬럼을 지우면 딸린 CHECK 제약도 함께 사라지므로,
    # 되돌릴 때 컬럼만 복원해서는 원래 스키마와 같아지지 않는다. 직접 다시 만든다.
    op.create_check_constraint(
        "ck_schedules_visibility", "nl_schedules", "visibility IN ('private', 'shared', 'public')"
    )
    op.create_check_constraint(
        "ck_diary_visibility", "nl_diary_entries", "visibility IN ('private', 'shared', 'public')"
    )
