"""스페이스 모델 및 컬럼 추가

Revision ID: 187f5272ce29
Revises: 343f93b240d6
Create Date: 2026-08-01 01:35:21.441276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187f5272ce29'
down_revision: Union[str, Sequence[str], None] = '343f93b240d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
