"""add menu table

Revision ID: 32aa082cae06
Revises: b88e93a35d0c
Create Date: 2026-08-03 00:04:55.401495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32aa082cae06'
down_revision: Union[str, Sequence[str], None] = 'b88e93a35d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nl_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='app', nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('required_role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('app', 'admin')", name='ck_menus_scope'),
    sa.ForeignKeyConstraint(['parent_id'], ['nl_menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_nl_menus_parent_id', 'nl_menus', ['parent_id'], unique=False)
    op.create_index('ix_nl_menus_scope_active_order', 'nl_menus', ['scope', 'is_active', 'sort_order'], unique=False)
    # ### end Alembic commands ###

    # 초기 메뉴 데이터를 함께 넣는다.
    # 메뉴가 비어 있으면 앱 하단 탭이 아예 그려지지 않으므로, 스키마와 같은
    # 마이그레이션에 담아 어느 환경에서든 동일한 기본 메뉴가 생기게 한다.
    # 화면 구성은 docs/DESIGN_SPEC.md 2.1절(캘린더·일정·설정 3개 탭)을 따른다.
    op.bulk_insert(
        sa.table(
            "nl_menus",
            sa.column("code", sa.String),
            sa.column("scope", sa.String),
            sa.column("name", sa.String),
            sa.column("icon", sa.String),
            sa.column("path", sa.String),
            sa.column("sort_order", sa.Integer),
        ),
        [
            {
                "code": "calendar",
                "scope": "app",
                "name": "캘린더",
                "icon": "calendar",
                "path": "/calendar",
                "sort_order": 1,
            },
            {
                "code": "schedules",
                "scope": "app",
                "name": "일정",
                "icon": "list",
                "path": "/schedules",
                "sort_order": 2,
            },
            {
                "code": "settings",
                "scope": "app",
                "name": "설정",
                "icon": "settings",
                "path": "/settings",
                "sort_order": 3,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nl_menus_scope_active_order', table_name='nl_menus')
    op.drop_index('ix_nl_menus_parent_id', table_name='nl_menus')
    op.drop_table('nl_menus')
    # ### end Alembic commands ###
