"""add missing fk for users default space

Revision ID: 343f93b240d6
Revises: 1287a7b788d8
Create Date: 2026-08-01 01:19:27.327538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343f93b240d6'
down_revision: Union[str, Sequence[str], None] = '1287a7b788d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_users_default_space', 'users', 'spaces', ['default_space_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_default_space', 'users', type_='foreignkey')
    # ### end Alembic commands ###
