"""add audit log table

Revision ID: b88e93a35d0c
Revises: 10cae1a9cf19
Create Date: 2026-08-02 23:54:05.331112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b88e93a35d0c'
down_revision: Union[str, Sequence[str], None] = '10cae1a9cf19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nl_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nl_audit_logs_action_created', 'nl_audit_logs', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_nl_audit_logs_ip_created', 'nl_audit_logs', ['ip_address', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_nl_audit_logs_resource', 'nl_audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_nl_audit_logs_user_created', 'nl_audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nl_audit_logs_user_created', table_name='nl_audit_logs')
    op.drop_index('ix_nl_audit_logs_resource', table_name='nl_audit_logs')
    op.drop_index('ix_nl_audit_logs_ip_created', table_name='nl_audit_logs')
    op.drop_index('ix_nl_audit_logs_action_created', table_name='nl_audit_logs')
    op.drop_table('nl_audit_logs')
    # ### end Alembic commands ###
